### ISSUE TITLE
Nim golfed implementation

### ISSUE THREAD

**Issue by DonaldTsang** [status-im/nim-keccak-tiny#10]
Is it possible to make a pure Nim implementation of Keccak like the ones in http://www.cypherspace.org/rsa/ ?

Source of short hash in Python for reference:
https://www.nayuki.io/res/cryptographic-primitives-in-plain-python/sha3hash.py
https://github.com/XKCP/XKCP/blob/master/Standalone/CompactFIPS202/Python/CompactFIPS202.py

**Comment by DonaldTsang** [comment]
External reference: https://github.com/coruus/keccak-tiny/issues/6 https://github.com/cirka/keccak-tiny/issues/1

**Comment by yglukhov** [comment]
cc @cheatfate

**Comment by arnetheduck** [comment]
see https://github.com/cheatfate/nimcrypto/blob/master/nimcrypto/keccak.nim

**Comment by DonaldTsang** [comment]
Well done @arnetheduck (if only those repeated function calls can get more compact)

**Comment by zah** [comment]
@DonaldTsang, take a look at the `digest` proc from the `hash` module in `nimcrypto`. It can be used like this:

```nim
keccak256.digest(bytes)
```

**Comment by DonaldTsang** [comment]
@zah Maybe a secondary template for lines 147-171 and 173-196 and 198-222, they are all loops of `range(24)` in Python speak if you understand what I mean
