### ISSUE TITLE
Possible hyphen identifier issue

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-keccak-tiny#2]
On my Mac, clang is sometimes trying to link with `nimcache/keccak-tiny.o` but the object file produced was named `nimcache/keccak_tiny_keccak_tiny.o`

![2018-02-12_14-43-55](https://user-images.githubusercontent.com/22738317/36099564-6d3b1ae0-1003-11e8-8a94-8278e41dbadb.png)

![2018-02-12_14-50-05](https://user-images.githubusercontent.com/22738317/36099753-052f9be6-1004-11e8-9941-319334bfbf55.png)

I prepared a PR to solve that but now somehow I don't have the issue anymore on master.
Branch: https://github.com/mratsim/nim-keccak-tiny/tree/hyphen_identifier_issue

**Comment by zah** [comment]
These are two separate files. `keccak_tiny_keccak_tiny.o` is the object file from compiling the nim module keccak_tiny.nim, while `keccak-tiny.o` is the result of compiling the included C source file of the original library (keccak-tiny.c).
